'use client';

import { formatDate } from '@/lib/utils';

interface PrintFooterProps {
    generatedAt: string;
}

export default function PrintFooter({ generatedAt }: PrintFooterProps) {
    return (
        <div className="hidden print:block mt-8 pt-6 border-t border-gray-300">
            <div className="flex justify-between items-start text-xs text-gray-600">
                <div className="space-y-1">
                    <p className="font-semibold text-sm">Generated by Ovira AI</p>
                    <p>Women's Health Intelligence Platform</p>
                    <p className="text-gray-500">ovira.ai</p>
                </div>
                
                <div className="space-y-1 text-right">
                    <p className="font-medium">Report Generated: {formatDate(generatedAt)}</p>
                    <p className="text-gray-500">Page <span className="page-number"></span></p>
                </div>
            </div>
            
            <div className="mt-4 p-3 bg-gray-50 border border-gray-300 rounded text-xs">
                <p className="font-semibold mb-1">⚕️ Medical Disclaimer</p>
                <p className="text-gray-700">
                    This report is generated by AI analysis and is for informational purposes only. 
                    It does not constitute medical advice, diagnosis, or treatment. 
                    Always consult with a qualified healthcare provider for medical decisions. 
                    The information is based on self-reported symptom logs and may not reflect complete medical history.
                </p>
            </div>
        </div>
    );
}
